### ISSUE TITLE
Nice work! Expect the code release

### ISSUE THREAD

**Issue by YanjieZe** [showlab/VideoSwap#1]

**Comment by Lucca-cherries** [comment]
Awesome, expecting the code. 👍

**Comment by smyja** [comment]
Same here, waiting for the code realease.

**Comment by mengVV** [comment]
Code, please

**Comment by Zwette** [comment]
Nice work. Is this going to be released soon?

**Comment by guyuchao** [comment]
Hi, all, thanks for waiting for our work. Now code is prepared and released. But with Meta's legal policy, the code is available as open-source on a per-request basis. Please fill in [this form](https://forms.gle/TB9fatZEzXTUwoj88) to provide your github username and email, we will invite you to the private repo.
